[package]
name = "switchbot-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
base64 = "0.13.0"
chrono = "0.4.22"
clokwerk = "0.4.0-rc1"
futures = "0.3.24"
reqwest = { version = "0.11.12", features = ["json"] }
ring = "0.16.20"
rocket = "0.5.0-rc.2"
serde = "1.0.145"
serde_json = "1.0.85"
thiserror = "1.0.36"
tokio = { version = "1.21.1", features = ["full"] }
uuid = { version = "1.1.2", features = ["v4"] }
