[package]
name = "switchbot-exporter"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
base64 = "0.21.0"
chrono = "0.4.24"
clokwerk = "0.4.0"
crossbeam-channel = "0.5.7"
ctrlc = { version = "3.2.5", features = ["termination"] }
futures = "0.3.27"
prometheus = "0.13.3"
reqwest = { version = "0.11.15", features = ["json"] }
ring = "0.16.20"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.158"
serde_json = "1.0.95"
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["full"] }
uuid = { version = "1.3.0", features = ["v4"] }
