[package]
name = "switchbot-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chrono = "0.4.22"
reqwest = { version = "0.11.12", features = ["json"] }
ring = "0.16.20"
rocket = "0.5.0-rc.2"
serde = "1.0.145"
serde_json = "1.0.85"
uuid = { version = "1.1.2", features = ["v4"] }
