[package]
name = "switchbot-exporter"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
base64 = "0.13.0"
chrono = "0.4.22"
clokwerk = "0.4.0"
crossbeam-channel = "0.5.6"
ctrlc = { version = "3.2.3", features = ["termination"] }
futures = "0.3.24"
prometheus = "0.13.3"
reqwest = { version = "0.11.12", features = ["json"] }
ring = "0.16.20"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = "1.0.145"
serde_json = "1.0.91"
thiserror = "1.0.38"
tokio = { version = "1.21.1", features = ["full"] }
uuid = { version = "1.2.2", features = ["v4"] }
