[package]
name = "switchbot-exporter"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
base64 = "0.21.2"
chrono = "0.4.26"
clokwerk = "0.4.0"
crossbeam-channel = "0.5.8"
ctrlc = { version = "3.4.0", features = ["termination"] }
futures = "0.3.27"
prometheus = "0.13.3"
reqwest = { version = "0.11.18", features = ["json"] }
ring = "0.16.20"
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = "1.0.164"
serde_json = "1.0.97"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
uuid = { version = "1.3.3", features = ["v4"] }
