version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SWITCHBOT_TOKEN
      - SWITCHBOT_SECRET
      - SWITCHBOT_METER_PLUS_DEVICE_ID
      - SWITCHBOT_PLUG_MINI_PC_DEVICE_ID
      - SWITCHBOT_PLUG_MINI_DESK_DEVICE_ID
      - RUST_BACKTRACE
