[tasks.up]
description = "Start the app on Docker"
command = "docker"
args = ["compose", "up", "-d", "--build"]

[tasks.down]
description = "Remove the app from Docker"
command = "docker"
args = ["compose", "down", "--rmi", "local"]

[tasks.logs]
description = "Show log of app"
command = "docker"
args = ["compose", "logs", "-ft", "--tail", "100"]
